### ISSUE TITLE
Idea: Use font-size: 0;

### ISSUE THREAD

**Issue by lifeiscontent** [inuitcss/objects.layout#2]
Here's an idea.

in the layout object do something like this for fixing the pseudo margins from inline-block elements.

``` scss
.layout {
  font-size: 0;
}

.layout__item {
  font-size: $inuit-base-font-size;
}
```

if the font-size on a specified element is different than that of a layout item it should overwrite it.
